Set required permissions (#175)
* Set required permissions

* fix typo

* Set contents permission to write

```bash
Pushing pull request branch to 'origin/actions/imgcmp/0e16922'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/actions/imgcmp/0e16922
  remote: Permission to 9sako6/imgcmp.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/9sako6/imgcmp/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```

* Add permissions to README examples